# TSLA Stock Prices: Analysis & Predictions

## Importing required libraries

In [1]:
import pandas as pd
import numpy as np

import yfinance as yf
from yahoofinancials import YahooFinancials

import plotly.graph_objects as go
import plotly.express as px

import chart_studio
import chart_studio.plotly as py

#credentials
chart_studio.tools.set_credentials_file(username='danielquerales', api_key='MlBK5QYwzzGDBdcf2hNs')

## Loading the Data from Yahoo Finance

In [2]:
df = yf.download('TSLA', progress=False)

## Data Cleaning and Preparation

### Check the dimensions

In [3]:
df.shape

(2942, 6)

### Check columns names

In [4]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

* Open: The price of the stock when the market opens in the morning
* Close: The price of the stock when the market closed in the evening
* High: Highest price the stock reached during that day
* Low: Lowest price the stock is traded on that day
* Volume: The total amount of stocks traded on that day

In [5]:
df.head(5)

             Open   High    Low  Close  Adj Close    Volume
Date
2010-06-29  3.800  5.000  3.508  4.778      4.778  93831500
2010-06-30  5.158  6.084  4.660  4.766      4.766  85935500
2010-07-01  5.000  5.184  4.054  4.392      4.392  41094000
2010-07-02  4.600  4.620  3.742  3.840      3.840  25699000
2010-07-06  4.000  4.000  3.166  3.222      3.222  34334500

In [6]:
df.tail(5)

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-02-28,815.010010,876.859985,814.710022,870.429993,870.429993,33002300
2022-03-01,869.679993,889.880005,853.780029,864.369995,864.369995,24922300
2022-03-02,872.130005,886.479980,844.270020,879.890015,879.890015,24881100
2022-03-03,878.770020,886.440002,832.599976,839.289978,839.289978,20373300
2022-03-04,849.099976,855.650024,825.160889,838.289978,838.289978,22393287

### Check for Nulls

In [7]:
df.isnull().values.any()

False

### Keep only from 2020-2022 for recent values

In [8]:
df = df.loc[df.index > '2020-01-01']

In [9]:
df.shape

(548, 6)

In [10]:
Min_date = df.index.min()
Max_date = df.index.max()
print ("First date is", Min_date)
print ("Last date is", Max_date)
print ("The period of time is", Max_date - Min_date)

First date is 2020-01-02 00:00:00
Last date is 2022-03-04 00:00:00
The period of time is 792 days 00:00:00

## Data Exploration & Visualizations

### Plot Historic Values

### Candlestick Chart

In [11]:
fig = go.Figure(data=[go.Candlestick(x=df.index,
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'])])

fig.update_layout(xaxis_rangeslider_visible=True, title="TSLA Candlestick Chart 2020-2022")
fig.update_yaxes(title_text="Stock_Price")
fig.update_xaxes(title_text="Date")
#fig.show()

py.iplot(fig, filename='tsla_candle')

## Summary of the data

In [12]:
df.describe()

,Open,High,Low,Close,Adj Close,Volume
count,548.000000,548.000000,548.000000,548.000000,548.000000,5.480000e+02
mean,566.074475,579.144028,551.834488,566.153079,566.153079,4.954235e+07
std,305.476642,311.816756,297.971792,305.019835,305.019835,3.721603e+07
min,74.940002,80.972000,70.101997,72.244003,72.244003,9.800600e+06
25%,292.959999,302.476509,283.897514,296.574501,296.574501,2.371980e+07
50%,626.929993,644.660004,611.000000,629.654999,629.654999,3.489440e+07
75%,777.822510,793.797501,764.237518,778.317505,778.317505,6.684530e+07
max,1234.410034,1243.489990,1217.000000,1229.910034,1229.910034,3.046940e+08

## How much has Tesla stock growth this two years?

In [13]:
(df['Open'].iloc[-1]*100)/df['Open'].iloc[0]

1000.1177388991189

### What is the all-time high stock price?

In [14]:
print ("The all time High value was:", df['High'].max(), 'USD [$]')

The all time High value was: 1243.489990234375 USD [$]

In [15]:
df[df['High'] == df['High'].max()]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-11-04,1234.410034,1243.48999,1217.0,1229.910034,1229.910034,25397400

### What is the all-time low stock price?

In [16]:
print ("The all time Low value was:", df['Low'].min(), 'USD [$]')

The all time Low value was: 70.10199737548828 USD [$]

In [17]:
df[df['Low'] == df['Low'].min()]

                 Open    High        Low      Close  Adj Close     Volume
Date
2020-03-18  77.800003  80.972  70.101997  72.244003  72.244003  118931000

## Plot Only Historic Adjusted Close values

Adjusted close is the closing price after adjustments for all applicable splits and dividend distributions.

In [18]:
fig = px.line(df, x=df.index, y=df['Adj Close'], title = 'Adjusted Close values')
#fig.show()

py.iplot(fig, filename='tsla_adj_close')

## Volume of Stock traded

Volume measures the number of shares traded in a stock or contracts traded in futures or options. Volume can indicate market strength, as rising markets on increasing volume are typically viewed as strong and healthy. When prices fall on increasing volume, the trend is gathering strength to the downside.

In [19]:
fig = px.line(df, x=df.index , y=df['Volume'], title = 'Volume of Stock traded')
#fig.show()

py.iplot(fig, filename='tsla_volume')

In [20]:
df[df['Volume'] == df['Volume'].max()]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-02-04,176.591995,193.798004,166.776001,177.412003,177.412003,304694000

## Market capitalization

Market capitalization (or market cap) is the total dollar value of all the shares of a company's stock. To calculate a company's market capitalization, multiply its stock's current price by the total number of outstanding shares.

In [21]:
df_add = df.copy()
df_add['MarketCap'] = df['Open'] * df['Volume']
df_add.head()

,Open,High,Low,Close,Adj Close,Volume,MarketCap
Date,,,,,,,
2020-01-02,84.900002,86.139999,84.342003,86.052002,86.052002,47660500,4.046377e+09
2020-01-03,88.099998,90.800003,87.384003,88.601997,88.601997,88892500,7.831429e+09
2020-01-06,88.094002,90.311996,88.000000,90.307999,90.307999,50665000,4.463283e+09
2020-01-07,92.279999,94.325996,90.671997,93.811996,93.811996,89410500,8.250801e+09
2020-01-08,94.739998,99.697998,93.646004,98.428001,98.428001,155721500,1.475305e+10

In [22]:
fig = go.Figure()

market_cap = go.Scatter(x=df_add.index , y=df_add['MarketCap'], name = 'Market Capitalization')

fig.add_trace(market_cap)

# Add title
fig.update_layout(title="Market Capitalization")  
fig.update_yaxes(title_text="MarketCap")
fig.update_xaxes(title_text="Date")
##fig.show()

py.iplot(fig, filename='tsla_mrketcp')

In [23]:
df_add[df_add['MarketCap'] == df_add['MarketCap'].max()]

,Open,High,Low,Close,Adj Close,Volume,MarketCap
Date,,,,,,,
2020-12-18,668.900024,695.0,628.539978,695.0,695.0,222126200,1.485802e+11

## Moving Averages

In statistics, a moving average is a calculation to analyze data points by creating a series of averages of different subsets of the full data set. It is also called a moving mean or rolling mean and is a type of finite impulse response filter. Variations include: simple, cumulative, or weighted forms.

In [24]:
df_add['MA50'] = df['Open'].rolling(50).mean()
df_add['MA200'] = df['Open'].rolling(200).mean()

In [25]:
fig = go.Figure()

adj_close = go.Scatter(x=df_add.index , y = df_add["Adj Close"], name = 'Adjusted Close')
ma_50 = go.Scatter(x=df_add.index , y = df_add["MA50"], name = 'Moving 50 day Averages')
ma_200 = go.Scatter(x=df_add.index , y = df_add["MA200"], name = 'Moving 200 day Averages')

# Add plots to the figure
fig.add_trace(adj_close)
fig.add_trace(ma_50)
fig.add_trace(ma_200)

# Add title
fig.update_layout(title="Moving Averages")
fig.update_xaxes(title_text="Date")
fig.update_yaxes(title_text="Stock_Price")
#fig.show()

py.iplot(fig, filename='tsla_mov')

## Returns per day

In [26]:
df_add['Returns'] = (df['Close']/df['Close'].shift(1)) -1

In [27]:
fig = px.histogram(df_add, x="Returns", marginal="box", hover_data=df.columns)
fig.update_yaxes(title_text="Frequency")
#fig.show()

py.iplot(fig, filename='tsla_voltile')

## Exponential Moving Average (EMA)

The exponential moving average (EMA) is a technical chart indicator that tracks the price of an investment (like a stock or commodity) over time. The EMA is a type of weighted moving average (WMA) that gives more weighting or importance to recent price data.

### Exponential moving average calculated over a 10-day period.

In [28]:
import pandas_ta

df_add.ta.ema(close='Adj Close', length=10, append=True)

Date
2020-01-02           NaN
2020-01-03           NaN
2020-01-06           NaN
2020-01-07           NaN
2020-01-08           NaN
                 ...
2022-02-28    847.268706
2022-03-01    850.378031
2022-03-02    855.743846
2022-03-03    852.752234
2022-03-04    850.122733
Name: EMA_10, Length: 548, dtype: float64

In [29]:
df_add.head(15)

,Open,High,Low,Close,Adj Close,Volume,MarketCap,MA50,MA200,Returns,EMA_10
Date,,,,,,,,,,,
2020-01-02,84.900002,86.139999,84.342003,86.052002,86.052002,47660500,4.046377e+09,NaN,NaN,NaN,NaN
2020-01-03,88.099998,90.800003,87.384003,88.601997,88.601997,88892500,7.831429e+09,NaN,NaN,0.029633,NaN
2020-01-06,88.094002,90.311996,88.000000,90.307999,90.307999,50665000,4.463283e+09,NaN,NaN,0.019255,NaN
2020-01-07,92.279999,94.325996,90.671997,93.811996,93.811996,89410500,8.250801e+09,NaN,NaN,0.038801,NaN
2020-01-08,94.739998,99.697998,93.646004,98.428001,98.428001,155721500,1.475305e+10,NaN,NaN,0.049205,NaN
2020-01-09,99.419998,99.760002,94.573997,96.267998,96.267998,142202000,1.413772e+10,NaN,NaN,-0.021945,NaN
2020-01-10,96.358002,96.987999,94.739998,95.629997,95.629997,64797500,6.243758e+09,NaN,NaN,-0.006627,NaN
2020-01-13,98.699997,105.125999,98.400002,104.972000,104.972000,132588000,1.308644e+10,NaN,NaN,0.097689,NaN
2020-01-14,108.851997,109.482002,104.980003,107.584000,107.584000,144981000,1.578147e+10,NaN,NaN,0.024883,NaN
2020-01-15,105.952003,107.568001,103.358002,103.699997,103.699997,86844000,9.201296e+09,NaN,NaN,-0.036102,96.535599
2020-01-16,98.750000,102.891998,98.433998,102.697998,102.697998,108683500,1.073250e+10,NaN,NaN,-0.009662,97.656035
2020-01-17,101.522003,103.134003,100.632004,102.099998,102.099998,68145500,6.918268e+09,NaN,NaN,-0.005823,98.464028
2020-01-21,106.050003,109.716003,105.681999,109.440002,109.440002,89017500,9.440306e+09,NaN,NaN,0.071890,100.459660
2020-01-22,114.377998,118.900002,111.820000,113.912003,113.912003,156845000,1.793962e+10,NaN,NaN,0.040863,102.905540
2020-01-23,112.849998,116.400002,111.120003,114.440002,114.440002,98255000,1.108808e+10,NaN,NaN,0.004635,105.002715

### Drop First 10 days of missing values

In [30]:
df.dropna(inplace=True)

C:\Users\Daniel\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [31]:
df_add.head()

,Open,High,Low,Close,Adj Close,Volume,MarketCap,MA50,MA200,Returns,EMA_10
Date,,,,,,,,,,,
2020-01-02,84.900002,86.139999,84.342003,86.052002,86.052002,47660500,4.046377e+09,NaN,NaN,NaN,NaN
2020-01-03,88.099998,90.800003,87.384003,88.601997,88.601997,88892500,7.831429e+09,NaN,NaN,0.029633,NaN
2020-01-06,88.094002,90.311996,88.000000,90.307999,90.307999,50665000,4.463283e+09,NaN,NaN,0.019255,NaN
2020-01-07,92.279999,94.325996,90.671997,93.811996,93.811996,89410500,8.250801e+09,NaN,NaN,0.038801,NaN
2020-01-08,94.739998,99.697998,93.646004,98.428001,98.428001,155721500,1.475305e+10,NaN,NaN,0.049205,NaN

In [32]:
df_add.tail()

,Open,High,Low,Close,Adj Close,Volume,MarketCap,MA50,MA200,Returns,EMA_10
Date,,,,,,,,,,,
2022-02-28,815.010010,876.859985,814.710022,870.429993,870.429993,33002300,2.689720e+10,964.021399,833.80980,0.074777,847.268706
2022-03-01,869.679993,889.880005,853.780029,864.369995,864.369995,24922300,2.167443e+10,961.524999,835.24115,-0.006962,850.378031
2022-03-02,872.130005,886.479980,844.270020,879.890015,879.890015,24881100,2.169955e+10,960.672198,836.72405,0.017955,855.743846
2022-03-03,878.770020,886.440002,832.599976,839.289978,839.289978,20373300,1.790345e+10,960.033599,838.27790,-0.046142,852.752234
2022-03-04,849.099976,855.650024,825.160889,838.289978,838.289978,22393287,1.901414e+10,958.678198,839.76065,-0.001191,850.122733

In [33]:
fig = go.Figure()

adj_close = go.Scatter(x=df_add.index , y = df_add["Adj Close"], name = 'Adjusted Close')
ema_10 = go.Scatter(x=df_add.index , y = df_add["EMA_10"], name = 'Exponential Moving Average (EMA)')

# Add plots to the figure
fig.add_trace(adj_close)
fig.add_trace(ema_10)

# Add title
fig.update_layout(title="Ajusted Close & Exponential Moving Average (EMA)")
fig.update_xaxes(title_text="Date")
fig.update_yaxes(title_text="Stock_Price")
#fig.show()

py.iplot(fig, filename='tsla_em')

## Machine Learning: LinearRegression

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

### Define Output and Inputs

In [35]:
y = df['Adj Close']
X = df.drop(['Adj Close', 'Close'], axis = 1)

### Split dataset

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [37]:
X_train.shape, X_test.shape

((438, 4), (110, 4))

In [38]:
y_train.shape, y_test.shape

((438,), (110,))

### Instantiate Linear Regression Model

In [39]:
model = LinearRegression().fit(X_train, y_train)

### Score

In [40]:
model.score(X_test, y_test)

0.9983385260190982

### Plot Results

In [41]:
y_test = y_test.sort_index()
X_test = X_test.sort_index()
y_pred = model.predict(X_test)

In [42]:
fig = go.Figure()

real_values = go.Scatter(x = X_test.index, y = y_test, name="Real Values")
pred_values = go.Scatter(x = X_test.index, y = y_pred, name="Predict Values")

# Add plots to the figure
fig.add_trace(real_values)
fig.add_trace(pred_values) 

# Add title
fig.update_layout(title="Tesla Stock Prices")                                           
#fig.show()

py.iplot(fig, filename='tsla_regression')