# Bubble  Chart

## Importing required libraries

In [1]:
import pandas as pd

import plotly
import plotly.graph_objs as go
import plotly.offline as offline

offline.init_notebook_mode(connected=True)

## Scatter plot

In [3]:
trace = go.Scatter(x = [15, 18, 21, 25], y = [100, 400, 300, 200], mode='markers')

data = [trace]

offline.iplot(data)

## Bubbles chart

### Add size of the Bubbles

In [4]:
z = [25, 100, 75, 50]

In [5]:
trace = go.Scatter(x = [15, 18, 21, 25], y = [100, 400, 300, 200], mode='markers', marker = dict(size=z))

data = [trace]

offline.iplot(data)

### Add more variables as colors

In [6]:
i = [5, 6, 8, 4]

In [8]:
trace = go.Scatter(x = [15, 18, 21, 25], y = [100, 400, 300, 200], mode='markers', 
                   marker = dict(size=z, color=i, colorscale='Portland', showscale=True))

data = [trace]

offline.iplot(data)

## Load some data

In [22]:
df = pd.read_xml('Datasets/cal_housing.xml')

## Check dimensions

In [23]:
df.sample(10)

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
10329,10329,-117.75,33.84,16.0,3491.0,502.0,1496.0,509.0,6.6207,270500.0
8793,8793,-118.39,33.79,30.0,4402.0,563.0,1582.0,551.0,10.8980,500001.0
10708,10708,-117.71,33.61,26.0,2280.0,550.0,669.0,502.0,2.3438,72300.0
16418,16418,-121.27,37.87,34.0,1010.0,206.0,678.0,234.0,2.9531,104000.0
1454,1454,-121.96,37.96,28.0,1838.0,273.0,899.0,270.0,5.2145,229200.0
12752,12752,-121.37,38.62,43.0,1077.0,199.0,447.0,182.0,3.0139,115600.0
16557,16557,-121.27,37.82,26.0,1170.0,238.0,830.0,216.0,2.6458,127500.0
10182,10182,-117.95,33.86,35.0,2478.0,431.0,1333.0,427.0,5.2099,191400.0
10589,10589,-117.77,33.69,16.0,1666.0,341.0,479.0,336.0,2.1406,55000.0
10893,10893,-117.87,33.72,37.0,2216.0,497.0,2445.0,506.0,3.8421,174000.0

In [26]:
df.drop('index', axis=1, inplace=True)

In [27]:
df.shape

(20640, 9)

In [28]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

## Select a random samples from data

In [29]:
df = df.sample(frac=0.07).reset_index(drop=True)

In [30]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-118.02,33.80,24.0,84.0,14.0,32.0,8.0,5.8750,193800.0
1,-120.12,41.40,33.0,2820.0,515.0,976.0,403.0,2.6062,52600.0
2,-118.38,33.79,32.0,10445.0,1620.0,4474.0,1576.0,7.7042,500001.0
3,-119.90,36.20,43.0,187.0,38.0,106.0,40.0,1.8750,137500.0
4,-116.61,33.93,35.0,321.0,71.0,157.0,61.0,2.8056,68100.0

In [31]:
df.shape

(1445, 9)

## Plot a Bubble Chart

In [36]:
trace = go.Scatter(x = df['median_income'], y = df['median_house_value'],
                  mode = 'markers', marker = dict(size = df['total_rooms'], sizeref=500,
                                                 color = df['housing_median_age'], colorscale = 'Jet', showscale=True))

data = [trace]

layout = go.Layout(height=600, width=900, title='Housing Data', hovermode ='closest')

fig = go.Figure(data = data, layout = layout)

offline.iplot(fig)